// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import util.Config;
import util.Login;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddMajorInfoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", Config.chromeDriverUrl);
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addMajorInfo() {
    //登陆
    Login login = new Login();
    login.login(driver);
    //等待页面加载，申请报考按钮出现，等待时间为10s
    WebDriverWait wait = new WebDriverWait(driver,10);
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("majorBtn1"))).click();

    driver.findElement(By.id("addMajorBtn")).click();

    //专业名称
    driver.findElement(By.id("majorId")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(1)")).click();

    //报考级别
    driver.findElement(By.id("examinationLevel")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(1)")).click();

    //考试方式
    driver.findElement(By.id("examinationType")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(2)")).click();

    //指导老师姓名
    driver.findElement(By.id("teacherName")).click();
    driver.findElement(By.id("teacherName")).sendKeys("刘老师");

    //指导老师电话
    driver.findElement(By.id("teacherPhone")).click();
    driver.findElement(By.id("teacherPhone")).sendKeys("15619783353");

    driver.findElement(By.id("track_1")).click();
    driver.findElement(By.id("track_1")).sendKeys("练习曲1");

    driver.findElement(By.id("track_2")).click();
    driver.findElement(By.id("track_2")).sendKeys("练习曲2");

    driver.findElement(By.id("track_3")).click();
    driver.findElement(By.id("track_3")).sendKeys("练习曲3");

    driver.findElement(By.id("signTime")).click();
    driver.findElement(By.id("signTime")).sendKeys("002020-09-10");

    driver.findElement(By.id("signMeet")).click();
    driver.findElement(By.id("signMeet")).sendKeys("小提琴委员会");

    driver.findElement(By.id("level")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(1)")).click();

    driver.findElement(By.id("majorUpload")).sendKeys(Config.certificateImgUrl);

    driver.findElement(By.id("updateBtn")).click();
    driver.findElement(By.id("rowBackBtn")).click();
    System.out.println("通过");
  }
}
