// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import util.Config;
import util.Login;

import java.util.HashMap;
import java.util.Map;

//新增学员测试
public class AddStudentTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", Config.chromeDriverUrl);
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addStudent() {
    //登陆
    Login login = new Login();
    login.login(driver);

    //等待页面加载，新增学员按钮出现，等待时间为10s
    WebDriverWait wait = new WebDriverWait(driver,10);
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("addStudentBtn"))).click();
    //姓名
    driver.findElement(By.id("studentNameInput")).click();
    driver.findElement(By.id("studentNameInput")).sendKeys("测试学员1");
    //姓名拼音
    driver.findElement(By.id("studentNameLetterInput")).click();
    driver.findElement(By.id("studentNameLetterInput")).sendKeys("ceshixueyuan1");
    //证件类型
    driver.findElement(By.id("typeOfCertificateSelect")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(1)")).click();
    //证件号码
    driver.findElement(By.id("idNumberInput")).click();
    driver.findElement(By.id("idNumberInput")).sendKeys("610327199805184329");
    //性别
    driver.findElement(By.id("sexSelect")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(1)")).click();
    //民族
    driver.findElement(By.id("nationSelect")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(1)")).click();
    //国籍
    driver.findElement(By.id("nationalitySelect")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(1)")).click();
    //生日
    driver.findElement(By.id("birthdayInput")).click();
    driver.findElement(By.id("birthdayInput")).sendKeys("002020-09-01");
    driver.findElement(By.id("studentPhotoFile")).sendKeys(Config.studentPhotoUrl);
    //提交
    driver.findElement(By.id("commitBtn")).click();
    //返回
    driver.findElement(By.id("backListBtn")).click();
    System.out.println("通过");
  }
}
