// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import util.Config;
import util.Login;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class VideoUploadTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", Config.chromeDriverUrl);
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void videoUpload() {
    //登陆
    Login login = new Login();
    login.login(driver);
    //等待页面加载，申请报考按钮出现，等待时间为10s
    WebDriverWait wait = new WebDriverWait(driver,10);
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("majorBtn1"))).click();
    driver.findElement(By.id("videoBtn1")).click();
    driver.findElement(By.id("studentVideoFile10")).sendKeys("C:\\fakepath\\守望.mp4");
    driver.findElement(By.id("studentVideoFile21")).sendKeys("C:\\fakepath\\123.mp4");
    driver.findElement(By.id("studentVideoFile32")).sendKeys("C:\\fakepath\\提交视频.mp4");
    driver.findElement(By.id("uploadTextRadio")).click();
    driver.findElement(By.id("commitVideoBtn")).click();
    System.out.println("通过");
  }
}
